// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNO772tATAl4wQr1U5RTF-Ul5E2pKjFVQ',
    appId: '1:631600544553:android:1a352d6c60fb8507851538',
    messagingSenderId: '631600544553',
    projectId: 'testproject-7b5d8',
    storageBucket: 'testproject-7b5d8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUbFNjyEVu2AGWqz1IHr0MzVV_JgjudMY',
    appId: '1:631600544553:ios:ef8e06a82f652dcb851538',
    messagingSenderId: '631600544553',
    projectId: 'testproject-7b5d8',
    storageBucket: 'testproject-7b5d8.firebasestorage.app',
    androidClientId: '631600544553-mhqveiauqpcnomaem42vo5mjkipcno8h.apps.googleusercontent.com',
    iosClientId: '631600544553-vqipb54emslpghsg8e8o5qm5jkkhdl34.apps.googleusercontent.com',
    iosBundleId: 'com.editor',
  );

}